### ISSUE TITLE
Wahaha

### ISSUE THREAD

**Issue by Kira8866** [ostdari/ostdari.github.io#1]
Доброго дня, ostdari.
Меня зовут Кирилл, я технический администратор кафе Wahaha.  Мы благодарны за ваш интерес к нашему бренду и продукту.
К сожалению ваша публичная работа вводит наших посетителей в заблуждение. Можете сделать эту работу приватной?

**Comment by ostdari** [comment]
Здравствуйте, @Kira8866!
Данная работа была сделана исключительно в учебных целях без какой-либо претенциозности, я уберу ее из публичного доступа по вашей просьбе
